### ISSUE TITLE
Specify the nightly rust version

### ISSUE THREAD

**Issue by yanganto** [Rust-for-Linux/nix#2]
Hi there,

This project is using nightly rust to build `rust-for-linux`.

There is no date for nightly rust in this project nor a `rust-toolchain` file in `rust-for-linux` to specify the nightly version. 

May we use something like `rust-overlay` to specify the nightly rust version like the following link?
https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix

Such that this project can provide a stable and consistent build environment.

Thank you.

**Comment by Kloenk** [comment]
For the nix builds I use a rustc stable checkout, but with nightly build flag. I think this is a good way of doing this.

**Comment by yanganto** [comment]
Thanks for the reply.  It is clear now, and I learn more from this.  Thanks. :pray:
